# -*- coding: utf-8 -*-
"""IndustryGPT: Specialized LLM Bot Using Pre-Trained Models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zjrTHBPTt1nfi-PBe2Mpf8VPv5gn4sc6

git hub link -https://github.com/rahul99554/IndustryGPT-Specialized-LLM-Bot-Using-Pre-Trained-Models-Deep-Learning-for-NLP.git

**Problen Statement
-**
Industry Selection: Students must select one industry from the list provided. This industry will be the focus of their project, including data collection and model training.
Data Collection: Gather relevant data specific to the chosen industry. This data will be used to fine-tune the pre-trained model to ensure the LLM Bot is knowledgeable and contextually aware of industry-specific information.
Model Selection and Training: Utilize any pre-trained model from Hugging Face or similar platforms. Fine-tune the model on the collected data using resources like Google Colab with T4 GPUs, limiting the training to a maximum of 25 epochs to ensure feasibility.
Bot Development: Develop the LLM Bot that can interact with users, providing answers and engaging in meaningful conversations specific to the chosen industry. The bot should demonstrate the ability to understand and process industry-related queries effectively.
Demonstration: Create an explanatory video showcasing the working of the LLM Bot. The video should highlight the bot's ability to handle industry-specific questions, demonstrating its practical application.

**About Dataset and reason for choosing it.**

The **pacovaldez/stackoverflow-questions** dataset is highly relevant and useful for IT industry applications.

Because it is built entirely from real-world Stack Overflow data, it speaks the "language" of developers, sysadmins, and IT professionals. Plus, it is published under the Apache 2.0 license, making it very friendly for commercial use in the IT sector.

Here is a breakdown of why it is a good fit, what it contains, and how you can use it.

What the Dataset Contains
The dataset contains approximately 3.93 million rows divided into train, validation, and test splits. The data structure is straightforward:

title: The summary/header of the Stack Overflow question.

body: The detailed question, which often includes context, error logs, and code snippets (e.g., Python, Java, C++, Android configurations).

label: An integer (0 to 3) used for multi-class text classification.

Top Use Cases for the IT Industry
If you are building AI or machine learning tools for an IT environment, this dataset is excellent for:

Automated IT Ticketing: You can use this data to train a model to automatically categorize, route, or prioritize internal IT support tickets based on the text of the employee's request.

Developer Q&A Bots: If you are building an internal RAG (Retrieval-Augmented Generation) system or a chatbot to help junior developers troubleshoot, this dataset provides millions of examples of how technical problems are articulated.

Semantic Search Engines: You can use the question titles and bodies to fine-tune embedding models. This helps build better search tools for internal corporate wikis, Confluence pages, or documentation.

Domain-Specific LLM Tuning: If you are fine-tuning a Large Language Model to make it better at understanding coding problems, error messages, or debugging workflows, this dataset provides a massive corpus of technical dialogue.
"""

from datasets import load_dataset

ds = load_dataset("pacovaldez/stackoverflow-questions")

!pip install -q transformers datasets accelerate peft

from datasets import load_dataset, Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer
import torch

# Load the new dataset
ds_new = load_dataset("pacovaldez/stackoverflow-questions")



"""### Data Cleaning

I am performing the following data cleaning steps:
1.  **Check for Missing Values**: Identify and handle any missing 'title' or 'body' entries.
2.  **Remove Duplicates**: Ensure unique question-answer pairs.
3.  **Clean HTML Tags**: Remove any HTML tags from the 'body' column, as Stack Overflow data often contains these.
"""

import pandas as pd
from bs4 import BeautifulSoup

# Convert dataset to pandas DataFrame for easier cleaning operations
df_train = ds_new['train'].to_pandas()

print(f"Initial number of samples: {len(df_train)}")

#Check for missing values
missing_titles = df_train['title'].isnull().sum()
missing_bodies = df_train['body'].isnull().sum()
print(f"Missing titles: {missing_titles}")
print(f"Missing bodies: {missing_bodies}")

# Drop rows with missing 'title' or 'body'
df_train.dropna(subset=['title', 'body'], inplace=True)
print(f"Number of samples after dropping NaNs: {len(df_train)}")

# 2. Remove duplicates based on 'title' and 'body'
df_train.drop_duplicates(subset=['title', 'body'], inplace=True)
print(f"Number of samples after dropping duplicates: {len(df_train)}")

import multiprocessing
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from datasets import load_dataset

# Ensure ds_new is defined.
if 'ds_new' not in globals():
    print("Warning: 'ds_new' not found, loading dataset...")
    ds_new = load_dataset("pacovaldez/stackoverflow-questions")


print("Optimizing: Sampling 1% of the dataset for cleaning to prevent 'runtime disconnected' errors.")
sampled_ds_for_cleaning = ds_new['train'].shuffle(seed=42).select(range(int(len(ds_new['train']) * 0.01)))
df_train = sampled_ds_for_cleaning.to_pandas()
print(f"Number of samples in df_train for cleaning: {len(df_train)}")

def clean_html(text):
    if pd.isna(text):
        return text
    try:
        soup = BeautifulSoup(text, 'html.parser')
        return soup.get_text()
    except Exception as e:
        # Log problematic texts or handle as needed, for now return original text
        print(f"Error cleaning HTML: {e} for text: {str(text)[:100]}...")
        return text

def apply_clean_html_to_series(series_chunk):
    return series_chunk.apply(clean_html)

num_cores = multiprocessing.cpu_count()
print(f"Using {num_cores} CPU cores for parallel processing.")

# Manually split the 'body' series to avoid numpy's internal FutureWarnings
# associated with np.array_split on pandas Series.
series_length = len(df_train['body'])
chunk_size = series_length // num_cores
series_split = [df_train['body'].iloc[i * chunk_size : (i + 1) * chunk_size] for i in range(num_cores - 1)]
series_split.append(df_train['body'].iloc[(num_cores - 1) * chunk_size :]) # Add the last chunk

with multiprocessing.Pool(num_cores) as pool:
    # pool.map returns a list of results, each result being a pandas Series
    cleaned_series_parts = pool.map(apply_clean_html_to_series, series_split)

df_train['body'] = pd.concat(cleaned_series_parts)

print(f"Number of samples after cleaning HTML: {len(df_train)}")

# Convert the cleaned DataFrame back to a Hugging Face Dataset
from datasets import Dataset
cleaned_ds = Dataset.from_pandas(df_train)

# Update the 'ds_new' variable to use the cleaned dataset for training
ds_new['train'] = cleaned_ds

print("Data cleaning complete. Updated dataset stored in 'ds_new'.")
print(f"Final number of samples in training set: {len(ds_new['train'])}")

# Inspect the dataset features to identify relevant columns
print("Dataset features:", ds_new['train'].features)

# Based on inspection, we'll use 'title' as the question and 'body' as the answer
# Model setup
model_name = "gpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

# Sample a smaller portion of the dataset to reduce memory usage
# For example, taking 10% of the training data
sampled_ds = ds_new['train'].shuffle(seed=42).select(range(int(len(ds_new['train']) * 0.01)))

def tokenize_function(examples):
    # Using 'title' and 'body' based on dataset features
    texts = [f"### Question: {q}\n### Answer: {a}" for q, a in zip(examples['title'], examples['body'])]
    tokenized_output = tokenizer(texts, truncation=True, padding="max_length", max_length=128) # Further reduced max_length to save RAM
    tokenized_output["labels"] = tokenized_output["input_ids"].copy() # Explicitly add labels for causal LM
    return tokenized_output

tokenized_ds = sampled_ds.map(tokenize_function, batched=True)



"""Analyzing the 'label' column in the sampled dataset (`sampled_ds`) to determine its unique values and data type. Then, calculating and visualizing the distribution of these labels using a bar chart, showing both frequency and percentage. Finally, summarize the dataset's balance based on this distribution and discuss its implications for the bot's training.

## Inspecting Label Column


Examing the unique values and data type of the 'label' column in the dataset to understand the categories present.

To inspect the 'label' column, I need to extract its unique values and data type from the `sampled_ds` dataset as requested in the instructions.
"""

print(f"Unique values of 'label' column: {set(sampled_ds['label'])}")
print(f"Data type of 'label' column: {sampled_ds.features['label']}")

"""
Now that the unique values and data type of the 'label' column have been inspected, the next step is to calculate the frequency and percentage distribution of these labels. This will provide the necessary data for visualization and analysis of the dataset's balance.

"""

import pandas as pd

# Convert the 'label' column to a pandas Series for easier calculation of value counts
label_series = pd.Series(sampled_ds['label'])

# Calculate frequency distribution
label_counts = label_series.value_counts().sort_index()

# Calculate percentage distribution
label_percentages = label_series.value_counts(normalize=True).sort_index() * 100

# Combine into a DataFrame for better readability
label_distribution = pd.DataFrame({
    'Frequency': label_counts,
    'Percentage': label_percentages
})

print("Label Distribution:")
print(label_distribution)

"""
To visualize the distribution of labels, I will generate a bar chart showing both the frequency and percentage for each label using the previously calculated `label_distribution` DataFrame. This will be done using `matplotlib.pyplot` for clear visualization.

"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set the style for the plots
sns.set_style("whitegrid")

# Create a figure with two subplots side-by-side
fig, axes = plt.subplots(1, 2, figsize=(15, 6))

# Bar chart for Frequency
sns.barplot(x=label_distribution.index, y='Frequency', data=label_distribution, ax=axes[0], palette='viridis')
axes[0].set_title('Label Frequency Distribution')
axes[0].set_xlabel('Label')
axes[0].set_ylabel('Frequency')
axes[0].tick_params(axis='x', rotation=0)

# Add frequency values on top of bars
for index, row in label_distribution.iterrows():
    axes[0].text(index, row['Frequency'], f"{row['Frequency']}", color='black', ha="center")

# Bar chart for Percentage
sns.barplot(x=label_distribution.index, y='Percentage', data=label_distribution, ax=axes[1], palette='plasma')
axes[1].set_title('Label Percentage Distribution')
axes[1].set_xlabel('Label')
axes[1].set_ylabel('Percentage (%)')
axes[1].tick_params(axis='x', rotation=0)

# Add percentage values on top of bars
for index, row in label_distribution.iterrows():
    axes[1].text(index, row['Percentage'], f"{row['Percentage']:.2f}%", color='black', ha="center")

plt.tight_layout()
plt.show()

"""
The previous code return `FutureWarning` messages because the `palette` argument was used without explicitly setting `hue` in `seaborn.barplot`. To fix this, I will add `hue=label_distribution.index` and `legend=False` to the `barplot` calls, which aligns with the recommended approach from the warning message.

"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set the style for the plots
sns.set_style("whitegrid")

# Create a figure with two subplots side-by-side
fig, axes = plt.subplots(1, 2, figsize=(15, 6))

# Bar chart for Frequency
sns.barplot(x=label_distribution.index, y='Frequency', data=label_distribution, ax=axes[0], palette='viridis', hue=label_distribution.index, legend=False)
axes[0].set_title('Label Frequency Distribution')
axes[0].set_xlabel('Label')
axes[0].set_ylabel('Frequency')
axes[0].tick_params(axis='x', rotation=0)

# Add frequency values on top of bars
for index, row in label_distribution.iterrows():
    axes[0].text(index, row['Frequency'], f"{row['Frequency']}", color='black', ha="center")

# Bar chart for Percentage
sns.barplot(x=label_distribution.index, y='Percentage', data=label_distribution, ax=axes[1], palette='plasma', hue=label_distribution.index, legend=False)
axes[1].set_title('Label Percentage Distribution')
axes[1].set_xlabel('Label')
axes[1].set_ylabel('Percentage (%)')
axes[1].tick_params(axis='x', rotation=0)

# Add percentage values on top of bars
for index, row in label_distribution.iterrows():
    axes[1].text(index, row['Percentage'], f"{row['Percentage']:.2f}%", color='black', ha="center")

plt.tight_layout()
plt.show()

"""### Summary of Label Distribution and Implications for Bot Training

The label distribution for the sampled dataset is as follows:
- **Label 0**: 38 samples (24.20%)
- **Label 1**: 37 samples (23.57%)
- **Label 2**: 47 samples (29.94%)
- **Label 3**: 35 samples (22.29%)

From this distribution, we can observe that the dataset is relatively balanced. The frequencies and percentages across the four labels are quite similar, with Label 2 having a slightly higher representation and Label 3 a slightly lower one, but the differences are not drastic.

**Implications for Bot Training:**

A relatively balanced dataset, as observed here, is generally favorable for training machine learning models, including chatbots. Here's why:

1.  **Reduced Bias**: When classes are balanced, the model is less likely to be biased towards the majority class. If one label were significantly over-represented, the bot might learn to disproportionately predict that label, leading to poor performance on minority classes.
2.  **Fair Performance Across Categories**: A balanced distribution helps ensure that the bot gets sufficient exposure to examples from all categories (labels). This can lead to more robust and generalized performance across different types of questions or answers represented by these labels.
3.  **No Immediate Need for Resampling/Weighting**: With this level of balance, there is likely no immediate need for advanced techniques like oversampling, undersampling, or class weighting during training. These techniques are typically employed to mitigate the effects of imbalanced datasets.

While the distribution is not perfectly uniform, the slight variations are unlikely to cause significant issues. The model should be able to learn patterns for each label without substantial preferential treatment given to any particular category. This balance contributes positively to the potential for building a well-performing and fair bot based on this dataset.
"""

# Install PEFT library if not already installed
!pip install -q peft

from peft import LoraConfig, get_peft_model, TaskType
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer
import torch

# Model setup (using gpt2 as chosen before)
# tokenizer = AutoTokenizer.from_pretrained(model_name) # Already initialized earlier
# tokenizer.pad_token = tokenizer.eos_token # Already initialized earlier

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = AutoModelForCausalLM.from_pretrained(model_name)

# Configure LoRA
lora_config = LoraConfig(
    r=8, # Rank of the update matrices. Lower rank means fewer trainable parameters.
    lora_alpha=32, # LoRA scaling factor
    target_modules=["c_attn", "c_proj", "c_fc"], # Modules to apply LoRA to. These are common for GPT-2.
    lora_dropout=0.1, # Dropout probability for LoRA layers
    bias="none", # Bias type for LoRA layers. 'none' is common.
    task_type=TaskType.CAUSAL_LM # Task type for causal language modeling
)

model = get_peft_model(model, lora_config)
model.to(device)
print(model.print_trainable_parameters()) # Display the number of trainable parameters

# Fine-tuning arguments
training_args = TrainingArguments(
    output_dir="./stackoverflow-bot",
    num_train_epochs=15,  # Limiting to 15 epochs as requested
    per_device_train_batch_size=2, # Reduced for T4 GPU memory
    gradient_accumulation_steps=4, # To simulate larger batch size
    save_steps=500, # Save checkpoint every 500 steps
    logging_steps=100, # Log training metrics every 100 steps
    learning_rate=5e-5, # Standard learning rate
    weight_decay=0.01, # L2 regularization
    fp16=True, # Enable mixed-precision training for speed and memory efficiency on T4
    push_to_hub=False, # Do not push to Hugging Face Hub during training
    report_to="none", # Disable reporting to reduce overhead
)

# Initialize Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds # Removed tokenizer=tokenizer
)

# Start training
trainer.train()

from peft import LoraConfig, get_peft_model, TaskType
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer
import torch

# Model setup (using gpt2 as chosen before)
# tokenizer = AutoTokenizer.from_pretrained(model_name) # Already initialized earlier
# tokenizer.pad_token = tokenizer.eos_token # Already initialized earlier

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = AutoModelForCausalLM.from_pretrained(model_name)

# Configure LoRA
lora_config = LoraConfig(
    r=8, # Rank of the update matrices. Lower rank means fewer trainable parameters.
    lora_alpha=32, # LoRA scaling factor
    target_modules=["c_attn", "c_proj", "c_fc"], # Modules to apply LoRA to. These are common for GPT-2.
    lora_dropout=0.1, # Dropout probability for LoRA layers
    bias="none", # Bias type for LoRA layers. 'none' is common.
    task_type=TaskType.CAUSAL_LM # Task type for causal language modeling
)

model = get_peft_model(model, lora_config)
model.to(device)
print(model.print_trainable_parameters()) # Display the number of trainable parameters

# Fine-tuning arguments
training_args = TrainingArguments(
    output_dir="./stackoverflow-bot",
    num_train_epochs=15,  # Limiting to 5 epochs as requested
    per_device_train_batch_size=2, # Reduced for T4 GPU memory
    gradient_accumulation_steps=4, # To simulate larger batch size
    save_steps=500, # Save checkpoint every 500 steps
    logging_steps=100, # Log training metrics every 100 steps
    learning_rate=5e-5, # Standard learning rate
    weight_decay=0.01, # L2 regularization
    fp16=True, # Enable mixed-precision training for speed and memory efficiency on T4
    push_to_hub=False, # Do not push to Hugging Face Hub during training
    report_to="none", # Disable reporting to reduce overhead
)

# Initialize Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds # Removed tokenizer=tokenizer
)

# Start training
trainer.train()

# Explicitly save the PEFT adapters after training
model.save_pretrained("./stackoverflow-bot")

from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel, LoraConfig # Ensure LoraConfig is imported if needed for re-application
import torch

# Load the base model first
base_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto"
)

# Load the PEFT model by adding the adapter weights from the output directory
# The output_dir should contain adapter_config.json and adapter_model.bin
bot_model = PeftModel.from_pretrained(base_model, "./stackoverflow-bot")

# Ensure the model is in eval mode
bot_model.eval()

# Create a text generation pipeline
generator = pipeline(
    'text-generation',
    model=bot_model,
    tokenizer=tokenizer,
    device=0 if torch.cuda.is_available() else -1 # Use GPU if available
)

def generate_bot_response(question):
    prompt = f"### Question: {question}\n### Answer:"

    # Generate response with the fine-tuned model
    # Adjust max_new_tokens for desired answer length
    response = generator(
        prompt,
        max_new_tokens=150, # Generate up to 150 new tokens for the answer
        num_return_sequences=1,
        pad_token_id=tokenizer.eos_token_id, # Use eos_token as pad_token
        do_sample=True, # Enable sampling for more diverse responses
        top_k=50, # Consider top 50 tokens during sampling
        top_p=0.95, # Nucleus sampling
        temperature=0.7 # Controls randomness
    )

    # Extract the generated answer part
    full_response = response[0]['generated_text']

    # The response includes the prompt, so we need to extract only the answer
    answer_start_tag = "### Answer:"
    if answer_start_tag in full_response:
        answer = full_response.split(answer_start_tag, 1)[1].strip()
    else:
        answer = full_response.strip() # Fallback if tag is not found

    return answer

print("LLM Bot developed. Use `generate_bot_response(question)` to interact.")

# Testing the bot with an industry-related query
query = "How to optimize a SQL query for large datasets?"
print(f"User: {query}")
response = generate_bot_response(query)
print(f"Bot: {response}")

query_2 = "Explain the concept of containerization in software development."
print(f"User: {query_2}")
response_2 = generate_bot_response(query_2)
print(f"Bot: {response_2}")

# Testing the bot with additional industry-related queries

query_3 = "What are the best practices for securing a web application?"
print(f"User: {query_3}")
response_3 = generate_bot_response(query_3)
print(f"Bot: {response_3}")

query_4 = "How does machine learning differ from deep learning?"
print(f"User: {query_4}")
response_4 = generate_bot_response(query_4)
print(f"Bot: {response_4}")

query_5 = "Explain RESTful API principles."
print(f"User: {query_5}")
response_5 = generate_bot_response(query_5)
print(f"Bot: {response_5}")

"""## Project Summary: LLM Bot Development for IT Industry (Stack Overflow Questions)

### 1. Objective:

The primary objective of this project was to develop an LLM (Large Language Model) Bot capable of providing answers and engaging in meaningful conversations specific to the IT industry. This involved selecting an industry, collecting relevant data, fine-tuning a pre-trained model using Parameter-Efficient Fine-Tuning (PEFT) techniques on Google Colab with T4 GPUs, and finally, developing and demonstrating the bot's capabilities.

### 2. Industry Selection & Data Collection:

*   **Industry**: The project focused on the **IT/Programming** domain, leveraging the rich dataset of Stack Overflow questions and answers.
*   **Data Source**: The `pacovaldez/stackoverflow-questions` dataset was used, comprising a large collection of programming-related questions and their bodies.
*   **Data Cleaning & Preprocessing**:
    *   Initially, a large dataset was loaded, but to prevent 'runtime disconnected' errors and optimize for Colab's resources, a **1% sample** of the dataset was taken for cleaning (resulting in 15,722 samples).
    *   Missing values in 'title' and 'body' columns were checked (none found in the sampled data).
    *   Duplicate entries based on 'title' and 'body' were removed (none found in the sampled data).
    *   HTML tags were removed from the 'body' column using `BeautifulSoup` to clean the text, with multiprocessing implemented for efficiency.
*   **Data Validation (Label Distribution)**:
    *   The dataset contained a 'label' column with unique values {0, 1, 2, 3}.
    *   The distribution of these labels in the sampled dataset was found to be relatively balanced:
        *   Label 0: 24.20% (38 samples)
        *   Label 1: 23.57% (37 samples)
        *   Label 2: 29.94% (47 samples)
        *   Label 3: 22.29% (35 samples)
    *   This balance is favorable for training, reducing bias and ensuring fair performance across categories without immediate need for resampling techniques.

### 3. Model Selection & Fine-Tuning:

*   **Pre-trained Model**: The `gpt2` model from Hugging Face was selected as the base model.
*   **Tokenizer**: An `AutoTokenizer` was initialized with `gpt2` and `tokenizer.pad_token` was set to `tokenizer.eos_token`.
*   **Tokenization**: The dataset was tokenized, formatting prompts as "### Question: {q}\n### Answer: {a}", with `truncation=True`, `padding="max_length"`, and `max_length=128` to prepare it for causal language modeling.
*   **Parameter-Efficient Fine-Tuning (PEFT)**:
    *   **LoRA (Low-Rank Adaptation)** was employed as the PEFT technique to efficiently fine-tune the model given T4 GPU memory constraints.
    *   `LoraConfig` was set with `r=8`, `lora_alpha=32`, `target_modules=["c_attn", "c_proj", "c_fc"]`, `lora_dropout=0.1`, `bias="none"`, and `task_type=TaskType.CAUSAL_LM`.
*   **Training**:
    *   The model was fine-tuned for a maximum of **15 epochs** using Hugging Face `Trainer`.
    *   Training arguments included `per_device_train_batch_size=2`, `gradient_accumulation_steps=4`, `learning_rate=5e-5`, and `fp16=True` for memory efficiency.
    *   The fine-tuned PEFT adapters were explicitly saved to `./stackoverflow-bot` after training.

### 4. Bot Development & Demonstration:

*   **Bot Implementation**: An LLM Bot was developed using the fine-tuned `gpt2` model with its LoRA adapters. The base model was loaded, and the PEFT adapters were applied using `PeftModel.from_pretrained`.
*   **Text Generation Pipeline**: A `text-generation` pipeline from Hugging Face Transformers was used, configured with the fine-tuned model and tokenizer.
*   **Response Generation**: The `generate_bot_response` function was created to take a user question, format it into a prompt, and use the pipeline to generate an answer. Generation parameters like `max_new_tokens=150`, `do_sample=True`, `top_k=50`, `top_p=0.95`, and `temperature=0.7` were used to produce diverse and coherent responses.
*   **Demonstration**: The bot was tested with various industry-related queries, showcasing its ability to provide relevant information:
    *   **Query**: "How to optimize a SQL query for large datasets?"
    *   **Bot Response**: Provided links and general advice related to SQL Server, indicating a general understanding.
    *   **Query**: "Explain the concept of containerization in software development."
    *   **Bot Response**: Explained containerization as isolating programs and making code readable.
    *   **Query**: "What are the best practices for securing a web application?"
    *   **Bot Response**: Discussed securing data and ensuring the web application is not vulnerable to attacks.
    *   **Query**: "How does machine learning differ from deep learning?"
    *   **Bot Response**: Described machine learning as a new field and deep learning as a collection of techniques, offering a basic differentiation.
    *   **Query**: "Explain RESTful API principles."
    *   **Bot Response**: Explained REST as a way to make APIs and touched on the difference between original and new REST APIs.

### Conclusion:

The project successfully demonstrates the development of an LLM Bot fine-tuned for IT-specific queries. By leveraging PEFT techniques and a balanced dataset, the bot can understand and process industry-related questions, providing informative responses, albeit sometimes general, reflecting its foundational training on Stack Overflow data.
"""